// The opening hang: one work from each of these traditions, interleaved so neighbours contrast
// (ancient next to modern, East next to West, paint next to clay). Order is intentional.
// `q` is the search term sent to each museum; `src` is the order of museums to try.
// `why` is a one-line wall text. Each line was checked against standard survey references;
// they state the textbook view, not contested scholarship.

export const OPENING = [
  { id: "impressionism", label: "Impressionism", years: "1860s–1880s", q: "Impressionism", src: ["aic", "nga", "wd", "met"],
    why: "Painting perception itself: light changing by the minute, set down in quick, visible strokes." },
  { id: "egypt", label: "Ancient Egypt", years: "c. 3000–30 BCE", q: "Egyptian", src: ["met", "cma", "aic"],
    why: "Much of it was made for eternity rather than for viewers, meant to be sealed in tombs." },
  { id: "ukiyo-e", label: "Ukiyo-e", years: "1600s–1800s", q: "Ukiyo-e", src: ["aic", "met", "cma"],
    why: "Cheap, popular woodblock prints of Edo Japan's 'floating world' that later reshaped European modern art." },
  { id: "baroque", label: "Baroque", years: "c. 1600–1750", q: "Baroque", src: ["nga", "aic", "wd"],
    why: "Drama by lighting: hard contrasts of light and dark pull you into the moment of action." },
  { id: "african", label: "Art of Africa", years: "various", q: "African mask figure", src: ["met", "cma", "aic"],
    why: "Many masks and figures were made to be used in performance and ritual, not hung on a wall." },
  { id: "cubism", label: "Cubism", years: "1907–1920s", q: "Cubism", src: ["wd", "aic", "met"],
    why: "Several viewpoints at once, with objects broken into faceted planes." },
  { id: "renaissance", label: "Italian Renaissance", years: "c. 1400–1550", q: "Renaissance", src: ["nga", "aic", "met"],
    why: "Linear perspective turned the flat picture plane into a convincing window." },
  { id: "ming", label: "Ming dynasty China", years: "1368–1644", q: "Ming dynasty", src: ["met", "cma", "aic"],
    why: "Scholar-painters prized brushwork as a trace of the painter's character, not only a picture of something." },
  { id: "hudson", label: "Hudson River School", years: "1825–1870s", q: "Hudson River School", src: ["met", "wd", "aic"],
    why: "America's first homegrown landscape movement, painting wilderness as national identity." },
  { id: "greek", label: "Ancient Greece", years: "c. 800–31 BCE", q: "Greek vase", src: ["met", "cma", "aic"],
    why: "Some vase painters signed their work, among the earliest named artists in the Western tradition." },
  { id: "symbolism", label: "Symbolism", years: "1880s–1910", q: "Symbolism", src: ["wd", "aic", "met"],
    why: "Dreams, myths and moods in place of observed reality." },
  { id: "mughal", label: "Mughal painting", years: "1500s–1800s", q: "Mughal", src: ["vam", "met", "cma"],
    why: "Court painters blended Persian, Indian and European ideas into jewel-like miniatures." },
  { id: "rococo", label: "Rococo", years: "c. 1720–1770", q: "Rococo", src: ["nga", "wd", "aic"],
    why: "Lighter, smaller and more playful: art for private salons rather than cathedrals." },
  { id: "expressionism", label: "Expressionism", years: "1905–1920s", q: "Expressionism", src: ["wd", "aic", "met"],
    why: "Distortion and harsh color used to show inner experience instead of outer appearance." },
  { id: "byzantine", label: "Byzantine", years: "330–1453", q: "Byzantine", src: ["met", "cma", "aic"],
    why: "Gold grounds stood for divine light, a space outside ordinary time." },
  { id: "realism", label: "Realism", years: "1840s–1880s", q: "Realism", src: ["nga", "aic", "wd"],
    why: "Ordinary people painted at the scale once reserved for kings and saints." },
  { id: "pre-columbian", label: "Ancient Americas", years: "before 1500", q: "Pre-Columbian", src: ["cma", "met", "aic"],
    why: "Ceramics, gold and textiles from cultures that developed with no contact with Europe." },
  { id: "dutch", label: "Dutch Golden Age", years: "c. 1600–1680", q: "Dutch Golden Age", src: ["aic", "nga", "met"],
    why: "A merchant republic bought art for homes, so painters specialized: still lifes, interiors, seascapes." },
  { id: "art-nouveau", label: "Art Nouveau", years: "1890–1910", q: "Art Nouveau", src: ["vam", "aic", "cma"],
    why: "Whiplash curves taken from plants, applied to everything from posters to furniture." },
  { id: "post-impressionism", label: "Post-Impressionism", years: "1886–1905", q: "Post-Impressionism", src: ["aic", "nga", "wd"],
    why: "Impressionism's color kept, then pushed toward structure, symbol or raw feeling." },
  { id: "roman", label: "Ancient Rome", years: "c. 500 BCE–476 CE", q: "Roman marble", src: ["met", "cma", "aic"],
    why: "Romans copied Greek sculpture so well that many lost Greek originals survive only through them." },
  { id: "neoclassicism", label: "Neoclassicism", years: "c. 1760–1830", q: "Neoclassicism", src: ["nga", "aic", "wd"],
    why: "A return to Greek and Roman order, often carrying a message about civic virtue." },
  { id: "islamic", label: "Art of the Islamic world", years: "600s onward", q: "Islamic calligraphy", src: ["met", "cma", "aic"],
    why: "In much religious art, calligraphy and geometric pattern carry the meaning that figures carry elsewhere." },
  { id: "fauvism", label: "Fauvism", years: "1905–1910", q: "Fauvism", src: ["wd", "aic", "met"],
    why: "Color freed from describing things; a critic called the painters 'wild beasts'." },
  { id: "gothic", label: "Gothic", years: "c. 1150–1450", q: "Gothic", src: ["nga", "met", "aic"],
    why: "Gilded panels and carvings made for altars and private devotion." },
  { id: "romanticism", label: "Romanticism", years: "c. 1790–1850", q: "Romanticism", src: ["wd", "nga", "aic"],
    why: "Feeling over reason: storms, ruins and the sublime terror of nature." },
  { id: "japanese-screens", label: "Japanese screens", years: "1500s–1800s", q: "Japanese screen", src: ["met", "cma", "aic"],
    why: "Folding screens turned whole rooms into landscapes, often painted on gold leaf." },
  { id: "pointillism", label: "Pointillism", years: "1886–1900s", q: "Pointillism", src: ["aic", "wd", "met"],
    why: "Dots of unmixed color meant to blend in your eye instead of on the palette." },
  { id: "pre-raphaelite", label: "Pre-Raphaelites", years: "1848–1900", q: "Pre-Raphaelite", src: ["vam", "aic", "met"],
    why: "Young English painters who rejected the academy for sharp detail and bright color." },
  { id: "qing", label: "Qing dynasty China", years: "1644–1912", q: "Qing dynasty", src: ["nga", "met", "cma"],
    why: "Imperial workshops produced porcelain, silk and painting of startling technical control." },
  { id: "tonalism", label: "Tonalism", years: "1880–1915", q: "Tonalism", src: ["aic", "wd", "met"],
    why: "Soft, misty American landscapes in a narrow range of color, built for mood." },
  { id: "arts-crafts", label: "Arts and Crafts", years: "1860–1920", q: "Arts and Crafts", src: ["vam", "aic", "cma"],
    why: "A protest against factory goods: handmade objects and honest materials." },
  { id: "northern-renaissance", label: "Northern Renaissance", years: "c. 1430–1580", q: "Netherlandish", src: ["met", "nga", "aic"],
    why: "Netherlandish painters pushed oil paint to render single hairs and tiny reflections." },
  { id: "precisionism", label: "Precisionism", years: "1915–1940", q: "Precisionism", src: ["aic", "met", "cma"],
    why: "Factories and bridges reduced to clean, sharp geometry." },
  // Added with the National Gallery, Wikidata and SMK sources
  { id: "folk", label: "American folk art", years: "1700s–1800s", q: "Naive art", src: ["nga"],
    why: "Self-taught painters made portraits and scenes for ordinary homes, with flat color and bold pattern." },
  { id: "danish-golden-age", label: "Danish Golden Age", years: "c. 1800–1850", q: "Eckersberg", src: ["smk"],
    why: "Copenhagen painters chased clear northern light and close observation of everyday Denmark." },
  { id: "futurism", label: "Futurism", years: "1909–1916", q: "Futurism", src: ["wd"],
    why: "Italian painters tried to paint speed, machines and the noise of the modern city." },
  { id: "vienna-secession", label: "Vienna Secession", years: "1897–1910s", q: "Vienna Secession", src: ["wd"],
    why: "Klimt's circle broke from the academy, mixing gold, flat pattern and the human body." },
  { id: "blaue-reiter", label: "Der Blaue Reiter", years: "1911–1914", q: "Der Blaue Reiter", src: ["wd"],
    why: "Kandinsky, Marc and Münter used color for emotion and pushed toward abstraction." },
];

// Broad, quality-leaning search terms used when browsing outside the opening hang.
export const BROWSE_TERMS = [
  "portrait", "landscape", "still life", "flowers", "sea", "river", "mountains", "garden", "city", "night",
  "winter", "horse", "bird", "dance", "music", "interior", "mother and child", "self-portrait", "boats",
  "harvest", "storm", "moon", "tiger", "cat", "dog", "fruit", "woman", "saint", "battle", "festival",
];

// Tones offered for Curator's Notes. `voice` is the instruction sent to the writer.
export const TONES = {
  cheeky: { label: "Dry and cheeky", voice: "Dry, witty, gently teasing, like a curator friend who knows too much. Never mean. Short sentences." },
  docent: { label: "Museum docent", voice: "Warm, clear and informative, like a good gallery talk. No jargon without a quick gloss." },
  critic: { label: "Art-school critic", voice: "Direct, formal analysis: composition, color, facture. Precise vocabulary, no flattery." },
  friend: { label: "Enthusiastic friend", voice: "Upbeat and encouraging, like a friend who just discovered art too. Plain words." },
};

export const WHY_CHIPS = ["Color", "Light", "Subject", "Mood", "Technique", "Composition", "Story"];
